### ISSUE TITLE
Project: Public-facing UI component library

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-js-sdk#1]
# Background & Goals

The goal of this project is to improve the developer experience for our customers, by giving them a component library they can easily import into their own projects. For now, the scope is limited to only the login buttons / login portal. Not only will this improve the integration experience, but it make all the app logins look more consistent. We may eventually use this in some of our other tools as well. 

```js
import { LoginPortal } from "@usekeyp/ui-library"

const LoginPage = () => {

  const onClick = (providerType) => {
   // custom auth logic depending on the app
  } 

  return (<><LoginPortal onClick={onClick} /><>)
}
```

#### Example use-case: Kaching

- Kaching is an app developed at ETH Denver Demo: https://kaching-eth-denver-trkd.vercel.app/login Repo: https://github.com/personnamedmike/KachingETHDenver
- The login portal implemented (left side) is very close to the correct designs (right side), but not perfect. 

![image](https://user-images.githubusercontent.com/35622595/227038774-8f5cdadb-7dde-451b-a881-8b6ba1aee995.png)

# Project Outline

### Stage 1 Components

- [ ] Ensure styleguidist is running properly
- [ ] Create a new package within the repo `/packages`
- [ ] Add all the components needed to create the login portal: eg. Button, Icon,
- [ ] Create a new component `<LoginPortal/>`
- [ ] The Buttons should accept the function needed to trigger a login. This is different depending on the implementation, so it must be general-purpose. Here's a few examples: 
      - Next app https://github.com/raid-guild/blood-of-moloch/pull/43/files
      - Redwood app https://github.com/UseKeyp/usekeyp-example-app-redwood/blob/dev/web/src/pages/LoginPage/LoginPage.js
      - Express app 
- [ ] Ensure the final results match designs

### Stage 2 Devops

- [ ] Get the publish-pr-packages tool working properly using Github actions
- [ ] Test the pr package created by this tool: Get it working in the Kaching app, or another example app. Share screenshots. If not using kaching, use any React app framework of your choice, excluding redwood. Ask Patrick to create a new private repo in our organization for pushing this.
- [ ] Pick a hosting provider to auto-deploy react-styleguidist for both `dev` and `main` branches. Add the deployment URLs to the readme. `dev` should be the default Github branch. `main` should be the production-ready branch.

### Stage 3 Delivery

- [ ] Create a readme with comprehensive usage information. Use our template services repo as the starting point.
- [ ] Update keyp-docs to include information about this library, and some sample usage. This doesn't need to be comprehensive, but needs to explain what this package is, what the benefits are, and how easy it is to use.
- [ ] Remove the private unused packages
- [ ] Destroy all git history, and make a new initial commit. This is to protect copyrighted code from a 3rd-party vendor being exposed.
- [ ] Ask Patrick to deploy the final version to npm.

**Comment by pi0neerpat** [comment]
Done!
